name: deployment
on:
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 37.60.251.94
          username: seyha
          key: ${{ secrets.SSH_KEY }}
          port: 1133
          script: |
            . ~/.nvm/nvm.sh
            whoami
            pwd
            ls
            cd dev-ops
            git pull
            pm2 restart dev-ops

