name: Test API
on:
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: localhost
          username: root
          password: admin
          port: 2233
          script: whoami