name: Test API
# When it's trigger
on:
  push:
    branches: main
  pull_request:
    branches: main
# Tasks
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    # To clone code to work on
    - name: Checkout repository
      run: ls
    